### ISSUE TITLE
Steno diagrams cut off without scroll bars

### ISSUE THREAD

**Issue by didoesdigital** [didoesdigital/typey-type#19]
# Background

Steno diagrams are cut off over a certain number:
![image](https://user-images.githubusercontent.com/2476974/74919507-d0612180-541e-11ea-9be6-4b928c907cd9.png)

The steno diagrams need to be cut them off _somewhere_ in case you look up something like `Lucy In the Sky with Diamonds` with 11 strokes and you're on a small screen. They also need to be legible (can't scale them all down to fit side by side). 

# Problem

By cutting them off a little bit, people might realise they can scroll/access the rest. Without scroll bars, however, this is not obvious and it looks like a visual bug.

# Approach

We could show a fade on the right edge only to encourage people to think there's more content available there.

![image](https://user-images.githubusercontent.com/2476974/74919479-c3443280-541e-11ea-91a1-b1d672a164d7.png)

- Needs to show the full diagrams at the start and end of the scroll area (i.e. when you scroll all the way to the right, it shows the full diagram, not hidden by a fade, not cut off at the edge).
- Needs to show the fade permanently on the right so that when you scroll it doesn't move with the diagrams.
- Needs to be responsive (small screens).
- Needs to work on for `StrokesForWords.js` used on Dictionaries index page, Lookup page, Flashcard pages.
- Needs to work on for lesson pages.

Here's as far as I got with an initial effort but it's not showing the full diagram on the right (covered by the fade when you can scroll no further):

![image](https://user-images.githubusercontent.com/2476974/74920336-208cb380-5420-11ea-98d1-8afdecd12bd7.png)

```scss
.fill-fade-right-edge {
  background-image: linear-gradient(to right,
    rgba(255,255,255,0) 0%,
    rgba(255,255,255,0) 90%,
    add-tint($brand-primary, 95%) 95%,
    add-tint($brand-primary, 95%) 100%);
  border-radius: 4px;
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  z-index: $z-index-fill-fade-edges;

  &.fill-fade-right-edge--white {
    background-image: linear-gradient(to right,
      rgba(255,255,255,0) 0%,
      rgba(255,255,255,0) 90%,
      rgba(255,255,255,0) 95%,
      rgba(255,255,255,0) 100%);
    border-radius: 4px;
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    z-index: $z-index-fill-fade-edges;
  }
}
```

```javascript
      <div className="fill-fade-parent">
        <span className="fill-fade-right-edge pointer-none"></span>
        <div className="flex overflow-auto mr05">
        ⋮
        </div>
      </div>
```
